# Generated by Django 2.1.5 on 2019-11-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20191127_0227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=120)),
                ('visitor_email', models.EmailField(max_length=254, unique=True)),
                ('visitor_phone', models.CharField(max_length=10)),
                ('check_in_time', models.TimeField()),
                ('check_out_time', models.TimeField()),
                ('host_name', models.CharField(max_length=120)),
                ('host_email', models.EmailField(max_length=254)),
                ('host_phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
